# Generated by Django 4.2.2 on 2023-07-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIAgnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('predictions', models.CharField(choices=[('No_DR', 'No_DR'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Proliferate_DR', 'Proliferate_DR')], default=None, max_length=20)),
                ('plot', models.ImageField(upload_to='plots/')),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default=None, max_length=40)),
                ('phone_number', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dr_assint',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default=None, max_length=40)),
                ('phone_number', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tablepatsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32)),
                ('age', models.CharField(max_length=3)),
                ('image', models.ImageField(default=None, upload_to='Photos/%y/%m/%d')),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=None, max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fn_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis_dr_protypesubqpp.doctors')),
                ('fn_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis_dr_protypesubqpp.diagnosis')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis_dr_protypesubqpp.tablepatsub'),
        ),
    ]
