# Generated by Django 4.2.2 on 2023-07-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_dr_protypesubqpp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tablepatsub',
            new_name='Patient',
        ),
    ]
